//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace MiniSAAS.DataServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObjectDescription", Namespace="http://schemas.datacontract.org/2004/07/MiniSAAS.Back.Classes")]
    public partial class ObjectDescription : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.Generic.Dictionary<string, string> FieldsField;
        
        private string ObjNameField;
        
        private int OrgIDField;
        
        private string PrimaryKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Fields {
            get {
                return this.FieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldsField, value) != true)) {
                    this.FieldsField = value;
                    this.RaisePropertyChanged("Fields");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjName {
            get {
                return this.ObjNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjNameField, value) != true)) {
                    this.ObjNameField = value;
                    this.RaisePropertyChanged("ObjName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrgID {
            get {
                return this.OrgIDField;
            }
            set {
                if ((this.OrgIDField.Equals(value) != true)) {
                    this.OrgIDField = value;
                    this.RaisePropertyChanged("OrgID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryKey {
            get {
                return this.PrimaryKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryKeyField, value) != true)) {
                    this.PrimaryKeyField = value;
                    this.RaisePropertyChanged("PrimaryKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataServiceReference.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDataService/RegisterTenant", ReplyAction="http://tempuri.org/IDataService/RegisterTenantResponse")]
        System.IAsyncResult BeginRegisterTenant(string emailid, string password, System.AsyncCallback callback, object asyncState);
        
        bool EndRegisterTenant(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDataService/LoginTenant", ReplyAction="http://tempuri.org/IDataService/LoginTenantResponse")]
        System.IAsyncResult BeginLoginTenant(string emailid, string password, System.AsyncCallback callback, object asyncState);
        
        int EndLoginTenant(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IDataService/CreateTable", ReplyAction="http://tempuri.org/IDataService/CreateTableResponse")]
        System.IAsyncResult BeginCreateTable(MiniSAAS.DataServiceReference.ObjectDescription od, System.AsyncCallback callback, object asyncState);
        
        bool EndCreateTable(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : MiniSAAS.DataServiceReference.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterTenantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public RegisterTenantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginTenantCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginTenantCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public bool Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<MiniSAAS.DataServiceReference.IDataService>, MiniSAAS.DataServiceReference.IDataService {
        
        private BeginOperationDelegate onBeginRegisterTenantDelegate;
        
        private EndOperationDelegate onEndRegisterTenantDelegate;
        
        private System.Threading.SendOrPostCallback onRegisterTenantCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoginTenantDelegate;
        
        private EndOperationDelegate onEndLoginTenantDelegate;
        
        private System.Threading.SendOrPostCallback onLoginTenantCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateTableDelegate;
        
        private EndOperationDelegate onEndCreateTableDelegate;
        
        private System.Threading.SendOrPostCallback onCreateTableCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<RegisterTenantCompletedEventArgs> RegisterTenantCompleted;
        
        public event System.EventHandler<LoginTenantCompletedEventArgs> LoginTenantCompleted;
        
        public event System.EventHandler<CreateTableCompletedEventArgs> CreateTableCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MiniSAAS.DataServiceReference.IDataService.BeginRegisterTenant(string emailid, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRegisterTenant(emailid, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool MiniSAAS.DataServiceReference.IDataService.EndRegisterTenant(System.IAsyncResult result) {
            return base.Channel.EndRegisterTenant(result);
        }
        
        private System.IAsyncResult OnBeginRegisterTenant(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string emailid = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((MiniSAAS.DataServiceReference.IDataService)(this)).BeginRegisterTenant(emailid, password, callback, asyncState);
        }
        
        private object[] OnEndRegisterTenant(System.IAsyncResult result) {
            bool retVal = ((MiniSAAS.DataServiceReference.IDataService)(this)).EndRegisterTenant(result);
            return new object[] {
                    retVal};
        }
        
        private void OnRegisterTenantCompleted(object state) {
            if ((this.RegisterTenantCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RegisterTenantCompleted(this, new RegisterTenantCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RegisterTenantAsync(string emailid, string password) {
            this.RegisterTenantAsync(emailid, password, null);
        }
        
        public void RegisterTenantAsync(string emailid, string password, object userState) {
            if ((this.onBeginRegisterTenantDelegate == null)) {
                this.onBeginRegisterTenantDelegate = new BeginOperationDelegate(this.OnBeginRegisterTenant);
            }
            if ((this.onEndRegisterTenantDelegate == null)) {
                this.onEndRegisterTenantDelegate = new EndOperationDelegate(this.OnEndRegisterTenant);
            }
            if ((this.onRegisterTenantCompletedDelegate == null)) {
                this.onRegisterTenantCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterTenantCompleted);
            }
            base.InvokeAsync(this.onBeginRegisterTenantDelegate, new object[] {
                        emailid,
                        password}, this.onEndRegisterTenantDelegate, this.onRegisterTenantCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MiniSAAS.DataServiceReference.IDataService.BeginLoginTenant(string emailid, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoginTenant(emailid, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int MiniSAAS.DataServiceReference.IDataService.EndLoginTenant(System.IAsyncResult result) {
            return base.Channel.EndLoginTenant(result);
        }
        
        private System.IAsyncResult OnBeginLoginTenant(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string emailid = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((MiniSAAS.DataServiceReference.IDataService)(this)).BeginLoginTenant(emailid, password, callback, asyncState);
        }
        
        private object[] OnEndLoginTenant(System.IAsyncResult result) {
            int retVal = ((MiniSAAS.DataServiceReference.IDataService)(this)).EndLoginTenant(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginTenantCompleted(object state) {
            if ((this.LoginTenantCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginTenantCompleted(this, new LoginTenantCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginTenantAsync(string emailid, string password) {
            this.LoginTenantAsync(emailid, password, null);
        }
        
        public void LoginTenantAsync(string emailid, string password, object userState) {
            if ((this.onBeginLoginTenantDelegate == null)) {
                this.onBeginLoginTenantDelegate = new BeginOperationDelegate(this.OnBeginLoginTenant);
            }
            if ((this.onEndLoginTenantDelegate == null)) {
                this.onEndLoginTenantDelegate = new EndOperationDelegate(this.OnEndLoginTenant);
            }
            if ((this.onLoginTenantCompletedDelegate == null)) {
                this.onLoginTenantCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginTenantCompleted);
            }
            base.InvokeAsync(this.onBeginLoginTenantDelegate, new object[] {
                        emailid,
                        password}, this.onEndLoginTenantDelegate, this.onLoginTenantCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MiniSAAS.DataServiceReference.IDataService.BeginCreateTable(MiniSAAS.DataServiceReference.ObjectDescription od, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateTable(od, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bool MiniSAAS.DataServiceReference.IDataService.EndCreateTable(System.IAsyncResult result) {
            return base.Channel.EndCreateTable(result);
        }
        
        private System.IAsyncResult OnBeginCreateTable(object[] inValues, System.AsyncCallback callback, object asyncState) {
            MiniSAAS.DataServiceReference.ObjectDescription od = ((MiniSAAS.DataServiceReference.ObjectDescription)(inValues[0]));
            return ((MiniSAAS.DataServiceReference.IDataService)(this)).BeginCreateTable(od, callback, asyncState);
        }
        
        private object[] OnEndCreateTable(System.IAsyncResult result) {
            bool retVal = ((MiniSAAS.DataServiceReference.IDataService)(this)).EndCreateTable(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateTableCompleted(object state) {
            if ((this.CreateTableCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateTableCompleted(this, new CreateTableCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateTableAsync(MiniSAAS.DataServiceReference.ObjectDescription od) {
            this.CreateTableAsync(od, null);
        }
        
        public void CreateTableAsync(MiniSAAS.DataServiceReference.ObjectDescription od, object userState) {
            if ((this.onBeginCreateTableDelegate == null)) {
                this.onBeginCreateTableDelegate = new BeginOperationDelegate(this.OnBeginCreateTable);
            }
            if ((this.onEndCreateTableDelegate == null)) {
                this.onEndCreateTableDelegate = new EndOperationDelegate(this.OnEndCreateTable);
            }
            if ((this.onCreateTableCompletedDelegate == null)) {
                this.onCreateTableCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateTableCompleted);
            }
            base.InvokeAsync(this.onBeginCreateTableDelegate, new object[] {
                        od}, this.onEndCreateTableDelegate, this.onCreateTableCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override MiniSAAS.DataServiceReference.IDataService CreateChannel() {
            return new DataServiceClientChannel(this);
        }
        
        private class DataServiceClientChannel : ChannelBase<MiniSAAS.DataServiceReference.IDataService>, MiniSAAS.DataServiceReference.IDataService {
            
            public DataServiceClientChannel(System.ServiceModel.ClientBase<MiniSAAS.DataServiceReference.IDataService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginRegisterTenant(string emailid, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = emailid;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("RegisterTenant", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndRegisterTenant(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("RegisterTenant", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLoginTenant(string emailid, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = emailid;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("LoginTenant", _args, callback, asyncState);
                return _result;
            }
            
            public int EndLoginTenant(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("LoginTenant", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateTable(MiniSAAS.DataServiceReference.ObjectDescription od, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = od;
                System.IAsyncResult _result = base.BeginInvoke("CreateTable", _args, callback, asyncState);
                return _result;
            }
            
            public bool EndCreateTable(System.IAsyncResult result) {
                object[] _args = new object[0];
                bool _result = ((bool)(base.EndInvoke("CreateTable", _args, result)));
                return _result;
            }
        }
    }
}
